# Generated by Django 5.2.17 on 2026-08-29 11:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('LOST', 'گمشده'), ('FOUND', 'پیدا شده')], default='LOST', max_length=10, verbose_name='نوع آگهی')),
                ('pet_type', models.CharField(choices=[('DOG', 'سگ'), ('CAT', 'گربه'), ('BIRD', 'پرنده'), ('OTHER', 'سایر')], max_length=10, verbose_name='نوع حیوان')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آگهی')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='نام حیوان')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='نژاد')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ و طرح')),
                ('gender', models.CharField(choices=[('MALE', 'نر'), ('FEMALE', 'ماده'), ('UNKNOWN', 'نامشخص')], default='UNKNOWN', max_length=10, verbose_name='جنسیت')),
                ('age', models.CharField(blank=True, max_length=50, verbose_name='سن تقریبی')),
                ('has_collar', models.BooleanField(default=False, verbose_name='قلاده دارد؟')),
                ('microchip_id', models.CharField(blank=True, max_length=100, verbose_name='شماره میکروچیپ')),
                ('special_features', models.TextField(blank=True, verbose_name='ویژگی\u200cهای ظاهری و رفتاری خاص')),
                ('event_date', models.DateTimeField(verbose_name='تاریخ و زمان حادثه')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='محله / منطقه')),
                ('address_description', models.TextField(blank=True, verbose_name='توضیحات دقیق محل')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='طول جغرافیایی')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس اضطراری')),
                ('reward', models.PositiveIntegerField(default=0, help_text='مبلغ به تومان', verbose_name='مژدگانی')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='پرونده مختومه شده؟ (پیدا شد)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_reports', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'آگهی حیوان',
                'verbose_name_plural': 'آگهی\u200cهای حیوانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets/%Y/%m/', verbose_name='تصویر')),
                ('is_main', models.BooleanField(default=False, verbose_name='تصویر اصلی؟')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.petreport', verbose_name='آگهی مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر حیوان',
                'verbose_name_plural': 'تصاویر حیوانات',
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(verbose_name='زمان مشاهده')),
                ('location_description', models.TextField(verbose_name='توضیحات محل مشاهده')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sightings/%Y/%m/', verbose_name='تصویر حیوان دیده\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت گزارش')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='pets.petreport', verbose_name='آگهی مربوطه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر گزارش\u200cدهنده')),
            ],
            options={
                'verbose_name': 'گزارش دیده\u200cشدن',
                'verbose_name_plural': 'گزارش\u200cهای دیده\u200cشدن',
                'ordering': ['-seen_at'],
            },
        ),
        migrations.AddIndex(
            model_name='petreport',
            index=models.Index(fields=['city', 'report_type'], name='pets_petrep_city_941b32_idx'),
        ),
        migrations.AddIndex(
            model_name='petreport',
            index=models.Index(fields=['latitude', 'longitude'], name='pets_petrep_latitud_5e1e0f_idx'),
        ),
    ]
