# Generated by Django 5.2.17 on 2026-08-28 23:34

import django.core.validators
import django.db.models.deletion
import pets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آگهی')),
                ('report_type', models.CharField(choices=[('LOST', 'گمشده'), ('FOUND', 'پیدا شده'), ('SIGHTED', 'فقط دیده شده')], default='LOST', max_length=10, verbose_name='نوع آگهی')),
                ('species', models.CharField(choices=[('DOG', 'سگ'), ('CAT', 'گربه'), ('BIRD', 'پرنده'), ('OTHER', 'سایر')], default='DOG', max_length=10, verbose_name='گونه حیوان')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='نژاد')),
                ('gender', models.CharField(choices=[('MALE', 'نر'), ('FEMALE', 'ماده'), ('UNKNOWN', 'نامشخص')], default='UNKNOWN', max_length=10, verbose_name='جنسیت')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ اصلی')),
                ('distinctive_features', models.TextField(blank=True, verbose_name='ویژگی\u200cهای ظاهری خاص (قلاده، جای زخم و...)')),
                ('has_microchip', models.BooleanField(default=False, verbose_name='دارای میکروچیپ')),
                ('event_date', models.DateField(verbose_name='تاریخ گم شدن یا پیدا شدن')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('district', models.CharField(blank=True, max_length=150, verbose_name='منطقه / محله')),
                ('address_description', models.TextField(blank=True, verbose_name='توضیحات دقیق محل')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='عرض جغرافیایی (Latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='طول جغرافیایی (Longitude)')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='شماره تماس جهت هماهنگی')),
                ('is_reward_offered', models.BooleanField(default=False, verbose_name='مژدگانی دارد؟')),
                ('reward_amount', models.CharField(blank=True, max_length=100, verbose_name='مبلغ یا نوع مژدگانی')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال / در جستجو'), ('RESOLVED', 'پیدا شد / بسته شد'), ('EXPIRED', 'منقضی شده')], default='ACTIVE', max_length=10, verbose_name='وضعیت پرونده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_reports', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'آگهی حیوان',
                'verbose_name_plural': 'آگهی\u200cهای حیوانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pets.models.pet_image_upload_path, verbose_name='تصویر')),
                ('is_cover', models.BooleanField(default=False, verbose_name='تصویر شاخص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.petreport', verbose_name='آگهی مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر آگهی',
                'verbose_name_plural': 'تصاویر آگهی',
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighted_at', models.DateTimeField(verbose_name='زمان رویت')),
                ('address_description', models.TextField(verbose_name='محل رویت')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('message', models.TextField(verbose_name='پیام یا توضیحات دیده\u200cشدن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='pets.petreport', verbose_name='آگهی مربوطه')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
            ],
            options={
                'verbose_name': 'گزارش دیده\u200cشدن',
                'verbose_name_plural': 'گزارش\u200cهای دیده\u200cشدن',
                'ordering': ['-sighted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='petreport',
            index=models.Index(fields=['report_type', 'species', 'status'], name='pets_petrep_report__930f37_idx'),
        ),
        migrations.AddIndex(
            model_name='petreport',
            index=models.Index(fields=['city', 'created_at'], name='pets_petrep_city_fadba8_idx'),
        ),
    ]
