# Generated by Django 5.2.17 on 2026-08-29 22:29

import pets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ImageField(upload_to='pets/%Y/%m/', validators=[pets.validators.validate_image_file], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sightings/%Y/%m/', validators=[pets.validators.validate_image_file], verbose_name='تصویر حیوان دیده\u200cشده'),
        ),
    ]
